'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { AlertTriangle, ArrowLeft, ArrowUpRight, Clock3, ExternalLink, HeartPulse, MapPin, Phone, Search, ShieldAlert } from 'lucide-react';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { hospitalItems } from '@/data/hospitals';
import { Footer } from './Footer';
import { Navbar } from './Navbar';
import { ImageWithFallback } from './ImageWithFallback';

export function HospitalPage() {
  const [query, setQuery] = useState('');
  const filteredItems = useMemo(() => hospitalItems.filter((item) => `${item.banglaName} ${item.type} ${item.union ?? ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [query]);

  return <div className="site-shell hospital-page"><Navbar /><main>
    <section className="hospital-hero"><div className="container hospital-hero-grid"><motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><Link className="back-link" href="/"><ArrowLeft size={15} /> হোমে ফিরে যান</Link><span className="eyebrow">হাসপাতাল ও চিকিৎসা / ডিরেক্টরি ০১</span><h1>সেবার তথ্য,<br /><em>বিশ্বাসের সঙ্গে।</em></h1><p>চৌগাছার স্বাস্থ্যসেবা সংক্রান্ত তথ্যকে একটি পরিষ্কার ও ব্যবহারযোগ্য directory-তে সাজানো হয়েছে। যোগাযোগের তথ্য যাচাই না হওয়া পর্যন্ত কোনো নম্বর বা map link দেখানো হবে না।</p><div className="hospital-hero-badges"><span><HeartPulse size={16} /> স্বাস্থ্যসেবা</span><span><ShieldAlert size={16} /> যাচাই-প্রথম</span></div></motion.div><motion.div className="hospital-hero-art" initial={{ opacity: 0, scale: .85, rotate: 5 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ duration: .85, delay: .15 }}><div className="hospital-pulse pulse-a" /><div className="hospital-pulse pulse-b" /><div className="hospital-cross"><HeartPulse size={72} strokeWidth={1.2} /></div><div className="hospital-float">সঠিক তথ্য<br /><strong>জরুরি</strong></div></motion.div></div></section>
    <section className="hospital-directory section-wrap"><div className="container"><div className="hospital-heading"><div><span className="eyebrow">সেবা খুঁজুন / ০২</span><h2>প্রয়োজনের সময়ে<br /><em>প্রয়োজনের তথ্য।</em></h2></div><p>হাসপাতাল, ধরন বা ইউনিয়নের অংশ লিখে search করুন। Data source: `data/hospitals.ts`</p></div><label className="hospital-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="হাসপাতাল বা ইউনিয়ন খুঁজুন" aria-label="হাসপাতাল বা ইউনিয়ন খুঁজুন" /></label><div className="hospital-result"><span><strong>{filteredItems.length}</strong>টি সেবা entry</span>{query && <button onClick={() => setQuery('')}>সার্চ মুছুন</button>}</div><div className="hospital-grid"><AnimatePresence mode="popLayout">{filteredItems.map((item, index) => <motion.article className="hospital-card" key={item.id} layout initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: .97 }} transition={{ duration: .28, delay: index * .05 }}><div className="hospital-image"><ImageWithFallback src={item.image} source={item.imageSource} alt={item.banglaName} sizes="(max-width: 700px) 90vw, (max-width: 1000px) 45vw, 40vw" /><span>{item.type}</span></div><div className="hospital-card-body"><div className="hospital-card-title"><h3>{item.banglaName}</h3><HeartPulse size={18} /></div><div className="hospital-detail-list"><p><MapPin size={15} /><span><b>ইউনিয়ন / ঠিকানা</b>{item.union ?? 'তথ্য যাচাই করা হচ্ছে'}{item.address ?? ''}</span></p><p><Phone size={15} /><span><b>ফোন</b>{item.phone ?? 'ফোন নম্বর যাচাই করা হচ্ছে'}</span></p><p><AlertTriangle size={15} /><span><b>জরুরি নম্বর</b>{item.emergency ?? 'জরুরি নম্বর যাচাই করা হচ্ছে'}</span></p><p><Clock3 size={15} /><span><b>সেবা সময়</b>{item.openingHours ?? 'সেবা সময় যাচাই করা হচ্ছে'}</span></p></div><div className="hospital-actions"><button className="hospital-action disabled" disabled title="Verified phone number is not available"><Phone size={15} /> কল করুন</button>{item.googleMapsUrl ? <a className="hospital-action" href={item.googleMapsUrl} target="_blank" rel="noreferrer"><ExternalLink size={15} /> Google Maps</a> : <button className="hospital-action disabled" disabled title="Verified Google Maps URL is not available"><ExternalLink size={15} /> Google Maps</button>}</div><span className="hospital-status">{item.source} <ArrowUpRight size={13} /></span></div></motion.article>)}</AnimatePresence></div>{filteredItems.length === 0 && <div className="hospital-empty"><Search size={25} /><h3>কোনো সেবা entry পাওয়া যায়নি</h3><p>অন্য নাম বা ইউনিয়ন দিয়ে আবার চেষ্টা করুন।</p></div>}</div></section>
    <section className="emergency-note"><div className="container emergency-note-grid"><div><span className="eyebrow">জরুরি ব্যবহারের আগে / ০৩</span><h2>ভুল তথ্যের চেয়ে<br /><em>তথ্য যাচাই ভালো।</em></h2></div><div><p>এই page-এ ফোন নম্বর, emergency number, address বা Google Maps link অনুমান করে দেওয়া হয়নি। Verified তথ্য যুক্ত হলে `data/hospitals.ts`-এ field আপডেট করুন। জরুরি অবস্থায় স্থানীয় সরকারি জরুরি সেবা বা নিকটস্থ কর্তৃপক্ষের সঙ্গে যোগাযোগ করুন।</p><div className="emergency-note-badge"><ShieldAlert size={18} /> Verified contact data pending</div></div></div></section>
  </main><Footer /></div>;
}
