'use client';

import { motion } from 'framer-motion';
import { ArrowLeft, ExternalLink, MapPin, Search } from 'lucide-react';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { unionItems, verifiedVillages } from '@/data/unions';
import { Footer } from './Footer';
import { Navbar } from './Navbar';

export function VillagesPage() { const [query, setQuery] = useState(''); const [unionId, setUnionId] = useState('সব'); const villages = useMemo(() => verifiedVillages.filter((village) => (unionId === 'সব' || village.unionId === unionId) && village.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [query, unionId]); return <div className="site-shell villages-page"><Navbar /><main><section className="villages-hero"><div className="container"><Link className="back-link" href="/"><ArrowLeft size={15} /> হোমে ফিরে যান</Link><span className="eyebrow">সব ইউনিয়নের গ্রাম / ডিরেক্টরি ০১</span><h1>গ্রাম খুঁজুন,<br /><em>ঠিক তথ্যের সঙ্গে।</em></h1><p>শুধু verified village entries এখানে দেখানো হবে। বর্তমানে সরকারি উৎসে ইউনিয়নভিত্তিক complete village list যাচাই করা হচ্ছে।</p></div></section><section className="all-villages-section section-wrap"><div className="container"><div className="village-controls"><label className="village-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="গ্রামের নাম খুঁজুন" aria-label="গ্রামের নাম খুঁজুন" /></label><select className="directory-select" value={unionId} onChange={(event) => setUnionId(event.target.value)} aria-label="ইউনিয়ন বাছাই করুন"><option value="সব">সব ইউনিয়ন</option>{unionItems.map((union) => <option value={union.id} key={union.id}>{union.name}</option>)}</select></div>{villages.length ? <div className="village-grid">{villages.map((village, index) => <motion.article className="village-card" key={village.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .03 }}><div className="village-card-body"><h3>{village.name}</h3><p><MapPin size={14} /> {village.unionName}</p>{village.googleMapsUrl && <a className="card-link" href={village.googleMapsUrl} target="_blank" rel="noreferrer">Google Maps-এ দেখুন <ExternalLink size={14} /></a>}</div></motion.article>)}</div> : <div className="village-empty"><Search size={27} /><h3>তথ্য যাচাই/সংযোজন করা হচ্ছে</h3><p>Official village list যাচাই হলে এই directory-তে গ্রামগুলো দেখানো হবে।</p></div>}</div></section></main><Footer /></div>; }
